version: '2'
services:
  node:
    hostname: "nodejs-server"
    build: .
    user: "node"
    command: "npm start"
    volumes:
      - nodemodules:/usr/app/node_modules
  #    - ./server/uploads:/usr/app/uploads
      - file_uploads:/usr/app/uploads
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://app@postgres/data
    networks:
      proxy:
        aliases:
          - node
      dbase:
  postgres:
    image: postgres:9.6.6-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: data
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
    networks:
      dbase:
        aliases:
          - database
  web:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes: 
      - ./server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html/static
    networks:
      - proxy
networks:
  dbase:
  proxy:
volumes:
  dbdata:
  nodemodules:
  file_uploads:



